### ISSUE TITLE
exception at term deposit

### ISSUE THREAD

**Issue by mjentsch** [ROIcoin/ROIcoin#6] opened 2017-12-20 21:52 UTC
ROIcoin version v1.1.0.000 (Dec  4 2017, 08:09:22)

I keep getting the following exception

2017-12-20 21:34:56 GUI: Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt. You must
reimplement QApplication::notify() and catch all exceptions there.

2017-12-20 21:34:56 

************************
EXCEPTION: St13runtime_error       
CWallet::GetCredit(): value out of range       

Anything I can do to provide more details?

Thanks

**Comment by ROIcoin** [comment] 2017-12-20 22:16
Hello mjentsch,

Which operating system are you on?  Please also indicate if 64 bit vs. 32 bit OS.  

For our own clarification, this is happening every time you attempt to Term Deposit?

In your list of Term Deposits, despite the wallet crashing, on restart, are you seeing the term deposits in the field?

Thank you for any additional information you can provide.

**Comment by mjentsch** [comment] 2017-12-20 22:45
Win7 64bit, using 64bit wallet version.
I just tried a small amount to term deposit and get the exception too. Restarting the wallet I see the new deposit in the list, the transaction is shown as "Conflicted"... yet the previous deposit got the status "Unconfirmed" in the list of transactions.
Not sure if it is related but I have the coins in hundreds of pieces (checked with coin control) due to the transfers from the pool. The amount I can deposit at once is limited, I get "Transaction too large" for higher numbers.

Regards

**Comment by ROIcoin** [comment] 2017-12-20 23:10
Thank you very much for the additional information.  We may have an issue in that we were attempting to keep pre-fork deposit term rates and post fork term rates, residing in the code.  There is obviously a conflict in the code.  I have duplicated your error on two other computers as well.

Our team is global, as soon as our counterparts across the pond are up.  We will address this issue immediately tonight.  Will keep you and Bitcointalk updated once the team has had a chance to review the code and discuss options.

Thank you for bringing this to our attention.

**Comment by ghobson2013** [comment] 2017-12-21 20:24
hi mjentsch  , I did some testing, and please confirm if you see the same behavior. before locking coins enable coin control and check if you have the first line show 5999999999 in the amount and interest column ( its MAX_MONEY-1 ).  This seems to be the case during the time it takes to confirm a previously locked deposit for 2 blocks, after which it dissappears as soon as you see 2 or 6 block confirms.

**Comment by mjentsch** [comment] 2017-12-21 22:19
Not happening here... I did another deposit of 100 coins, got the exception and after restart of the wallet saw the transactions with status "conflicted". I cleanly closed the wallet, started it again and the transactions got status "unconfirmed". Waited 2 blocks nothing changed, did a 2nd deposit of 200 coins, exception, restart, all new 4 transactions with status "unconfirmed". After each step I checked coin control and never saw the big amount you mentioned... finally got the transaction on the chain with block 27031, still no "big amount line" in coin control...

**Comment by ghobson2013** [comment] 2017-12-22 08:54
ok , you may need to do a -rescan -zapwallettxes=2   first  to start with a clean state , before trying again.  I will continue my testing. Thanks for the feedback.

**Comment by mjentsch** [comment] 2017-12-22 18:22
I did the -rescan -zapwallettxes=2 and went through the same steps as yesterday... my wallet refuses to show the "big amount line" in coin control :\

**Comment by ghobson2013** [comment] 2017-12-22 19:35
ok thanks for trying, and you still seeing conflicted transaction or are you still seeing the exception while trying to deposit coins ?

**Comment by mjentsch** [comment] 2017-12-22 23:08
I get the exception submitting the deposit, see most of the time the according transactions (deposit and change) as "Conflicted" when the wallet is restarted after the exception. When I close the wallet then and restart the transactions are "Unconfirmed".

**Comment by ghobson2013** [comment] 2017-12-23 16:28
can you run with -debug , or if you already have, upload the debug.log ? 
After restart unconfirmed is normal since it needs 6 confirmation to get confirmed.

**Comment by ghobson2013** [comment] 2017-12-23 16:36
Hi , we are currently testing a beta version , can you let us know if it resolves your issue ?
https://roi-coin.com/downloads/ROIcoin-qt_issue7-highfee_v2.zip
Please run with -debug , it will also create a new local logfile called transactionlog.txt from where you start the wallet.  If you still see the issue provide me with debug.log and transactionlog.txt 
Thankyou for your cooperation.

**Comment by mjentsch** [comment] 2017-12-23 23:05
Good news, this beta version doesn't show the problem... :)
Looking forward for the release...

Thanks!
Mario

**Comment by ghobson2013** [comment] 2017-12-24 11:52
Great thank you for confirming, we are working hard to get the release out today.

**Comment by ghobson2013** [comment] 2017-12-30 08:13
closing fixed in 1.1.1

**Closed as completed by ghobson2013** 2017-12-30 08:13 UTC
Labels: bug, high priority
